### ISSUE TITLE
Verification system does not remove from temporary cache when someone is manually verified.

### ISSUE THREAD

**Issue by AraHaan** [Cheeselab/DecoraterBot#5]
same as the issue title... Just do not want to type it again here. 👍

**Comment by AraHaan** [comment]
ah looks like the issue is in Discord.py itself. ```py
Ignoring exception caused at ignore_code:
Traceback (most recent call last):
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\DecoraterBotCore\Ignore.py", line 445, in ignore_code
    yield from BotCommandData.cheesy_commands(client, message)
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\DecoraterBotCore\Ignore.py", line 417, in cheesy_commands
    yield from self.bot.cheesy_commands_code(client, message)
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\DecoraterBotCore\Ignore.py", line 364, in cheesy_commands_code
    yield from client.send_message(message.author, msg_data)
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\discord\client.py", line 829, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\discord\client.py", line 246, in _resolve_destination
    channel = yield from self.start_private_message(destination)
  File "E:\Users\Elsword\Desktop\DecoraterBot\Async\resources\Dependencies\discord\client.py", line 778, in start_private_message
    channel = PrivateChannel(id=data['id'], user=user)
TypeError: __init__() missing 1 required positional argument: 'me'
```

**Comment by AraHaan** [comment]
Fixed in #6.
